### PR TITLE
Remove "no recruiting" from stage time description.

### PR DESCRIPTION
**Pull request by bucaran**
@briandeheus @maxhodges

### CODE REVIEW

**Comment by briandeheus** [comment]
I want a conversation on why this should be removed. I like the style of "no overtly obvious recruiting" as it sets a certain expectation of the event.

If this comes at the cost of fewer sponsors, we should poll the community on what is more important to them: 0円 access or possibility of many tech recruiters at the events. 

One thing that annoyed me during the Christmas meetup was being asked by 2 different people from a big recruiting firm whether I was looking for a job.

Thoughts?

**Comment by Maxhodges** [comment]
> One thing that annoyed me during the Christmas meetup was being asked by 2 different people from a big recruiting firm whether I was looking for a job.

Is saying "no thanks" that hard? What if you or other devs at the event _were_ looking for a job? Why should the topic be taboo? Should I not be allowed to invite you to my BBQ party because you have other plans and are therefore annoyed?

People at social gatherings can say a lot of annoying things. Why not censor political discussion, references to Pokemon Go, any chat about sports and whatever people are watching on Netflix this week because I'm not interested in those things?

**Comment by bucaran** [comment]
It's just 2 minutes. If you metric a typical tech presentation, you all know heaps of times are lost in  long-winged self-introductions, funny pictures in-between slides, or worse, making a comment about the funny picture. We can always put it back if we realize it was a mistake. You know, like science.

**Comment by lunardog** [comment]
I think we are talking about two kinds of recruiting: one is a single slide saying: "As you can see, we are doing cool stuff. Contact us if you want to work with us". 

Another are the recruiters going to Javascript meetups, collecting contact information for their database to randomly send e-mails about high-paid Java programming jobs. I know that the job of an IT recruiter is hard and not to be joked about, but may be annoying for both for those who are not looking for work, and for those who are, but keep getting the wrong leads. 

Can we soften the "no recruiting" rule to allow for recruiting to speakers' own teams, for jobs related to the meeting topic? Would that be a good middle solution?

**Comment by Maxhodges** [comment]
yeah, I see that could be annoying. But the page which said "(no recruiting)" was on a page about what you could/couldn't do as an event sponsor during your two-minute talk. 

I also think 2 minutes isn't very much time to allocate someone who might be spending 1-2 man yen on an event. Why not give them up to 6 minutes if they want it?

**Comment by Maxhodges** [comment]
Actually, if recruiters want to come and recruit, how about if you formalize that into some kinda program i.e. 

Attention Recruiters: you are welcome to come to our event and pitch your organization any relevant open positions you have. The cost is 6000 and you'll have 5 minutes to talk to the group as a whole and collect business cards. However it's up to each individual whether they will actually give you their contact information. 

alternatively you could ask for 5% of the first year's total compensation for any candidate scouting at your tokyojs ;)

**Comment by bucaran** [comment]
Does anyone have a good reason why we should keep the "no recruiting" in there? I'd prefer to remove it.

**Comment by briandeheus** [comment]
Fair enough. The people have spoken. :+1:

**Comment by Maxhodges** [comment]
btw, noticed you are using jekyll. Where do you guys host? We starting hosting all our statis sites at Netlify, an ultra performant platform for static sites. 

Maybe take a look

Features include
- Global CDN
- Ultra Fast DNS
- High Availability
- Atomic Deploys
- Instant Cache Invalidation
- Security
- Scalability
- Automation

Free one-click SSL, form submission hooks, and GitHub integration

**Comment by briandeheus** [comment]
We're using GitHub pages. 👍

**Comment by bucaran** [comment]
FWIW I am not a big fan of Jekyll, but it's easy / free to setup with github, so that's why.

**Comment by Maxhodges** [comment]
makes sense!

*Max Hodges* | Partner at White Rabbit Japan <http://whiterabbitjapan.com> |
t 03.6450.7109 | m 090.1795.4446

**Comment by Maxhodges** [comment]
> not a fan of Jekyll

Seems you can host anything there. I got React components running there
https://white-rabbit-japan.github.io/Semantic-UI-React-Storybook/?selectedKind=Progress%20Variations&selectedStory=Inverted&full=0&down=1&left=1

so you could probably use any static site tools you want

**Comment by briandeheus** [comment]
First time I heard about React storybook. Nice! Going to make use of that.

**Comment by Maxhodges** [comment]
yeah it's brilliant. can develop and test your Ui components without even running your app. Which allows near instant builds -- using webpack to build my LESS files.

I develop the stories in storybook basically just writing html in React , then my lead dev takes over and refactors them into proper React components with props etc.

**Comment by bucaran** [comment]
@Maxhodges Yes, you are right, it's not impossible to use another tool like, say Hugo, since the output is just HTML and CSS but GitHub is heavily biased towards Jekyll (for obvious reasons) and Jekyll suppot is "built-in". Also the tutorials I've found online to hook up GitHub with another static site generator suck for this same reason. On the other hand, it seems Gitlab pages offers built in support for a lot of static site generators.

See [Gitlab Pages](https://about.gitlab.com/2016/04/07/gitlab-pages-setup/)
> GitLab Pages supports static websites and builds any Static Site Generator (SSG), such as Jekyll, Hugo, Hexo, Middleman and Pelican.

Related
* https://help.github.com/articles/using-a-static-site-generator-other-than-jekyll/

**Pull request merged**
