### PR TITLE
Fix attendees link

### PR DESCRIPTION
**Pull request by fritz-c**
The attendees link was dead apparently because the permalink setting was incorrect.

On a side note, I heard something about a change in the recruiting policy. Does this page need an update as well?

### CODE REVIEW

**Comment by bucaran** [comment]
Thanks. No big changes. If you are a _sponsor_, you are allowed 2 minutes to pitch your business, essentially, you can say "we have cookies and we are hiring" and that's fine.

**Comment by fritz-c** [comment]
Alright. I wasn't personally interested in recruiting, I was just curious.

**Comment by bucaran** [comment]
Sure, no worries :)

**Comment by lunardog** [comment]
191kjp

**Pull request merged**
